// Traces the goodthemes logo (assets/logo.png: white "gt" on a black rounded square, transparent
// outside) into two vector shapes, the square and the letters, and writes:
//   playground/src/logo-paths.ts   for the themed <Logo /> in the playground
//   playground/public/favicon.svg  the tab icon, in the logo's own black and white
//   assets/logo.svg                the same, as a standalone file
//
//   node scripts/trace-logo.mjs
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import Jimp from "jimp";
import potrace from "potrace";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const UNITS = 100;
const source = await Jimp.read(join(root, "assets/logo.png"));
const { width: W, height: H } = source.bitmap;

/** Traces the pixels `pick` selects, returning a path on a UNITS x UNITS grid. */
async function trace(pick) {
  const mask = new Jimp(W, H, 0xffffffff);
  source.scan(0, 0, W, H, (x, y, i) => {
    const [r, g, b, a] = source.bitmap.data.subarray(i, i + 4);
    if (pick((r + g + b) / 3, a)) mask.setPixelColor(0x000000ff, x, y);
  });
  // potrace bundles its own Jimp, so hand it a PNG.
  const png = await mask.getBufferAsync(Jimp.MIME_PNG);
  const svg = await new Promise((resolve, reject) =>
    potrace.trace(png, { threshold: 128, turdSize: 40, optTolerance: 0.3, color: "#000" }, (err, out) => (err ? reject(err) : resolve(out))),
  );
  const k = UNITS / W;
  return svg
    .match(/ d="([^"]+)"/)[1]
    .replace(/-?\d+(\.\d+)?/g, (n) => String(+(Number(n) * k).toFixed(2)))
    .replace(/\s+/g, " ")
    .trim();
}

const square = await trace((_lum, alpha) => alpha > 128);
const letters = await trace((lum, alpha) => alpha > 128 && lum > 128);

writeFileSync(
  join(root, "playground/src/logo-paths.ts"),
  `// Generated by scripts/trace-logo.mjs from assets/logo.png. Do not edit by hand.
/** The logo's rounded square, on a ${UNITS} x ${UNITS} grid. */
export const LOGO_SQUARE = "${square}";
/** The "gt" letters, on the same grid. */
export const LOGO_LETTERS = "${letters}";
`,
);

const standalone = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${UNITS} ${UNITS}"><path fill="#111" d="${square}"/><path fill="#fff" d="${letters}"/></svg>\n`;
writeFileSync(join(root, "playground/public/favicon.svg"), standalone);
writeFileSync(join(root, "assets/logo.svg"), standalone);
console.log(`square ${square.length} chars, letters ${letters.length} chars`);
